# -*- coding: utf-8 -*-
"""Module2-RESTNET50.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15zHICJI9L57kQ2bZT3meclY9f5HBv6xR
"""

# Import library
from google.colab import files
from zipfile import ZipFile
import cv2

# Upload Segmentation zip file
uploaded = files.upload()

# Specify zip file name
file_name = "SegmentationNew.zip"

# Extract dataset
with ZipFile(file_name, 'r') as zip:
    zip.printdir() # Print all files in the zip file
    print('Extracting all files...')
    zip.extractall("LeafSegmentationDisease") # Extracts all files into a new folder
    print('Dataset extracted successfully!')

import os
# Setting constants
BATCH_SIZE = 32
Image_size = 224
input_shape = (Image_size, Image_size)
dataset_root = "/content/LeafSegmentationDisease/Segmentation"

train_dir = os.path.join(dataset_root, "Training")
test_dir = os.path.join(dataset_root, "Validation")

from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications.resnet50 import preprocess_input

# Define augmentations for train dataset and read the images
train_aug = ImageDataGenerator(
    preprocessing_function=preprocess_input,
    rotation_range=20,
    width_shift_range=0.2,
    height_shift_range=0.2,
    shear_range=0.2,
    zoom_range=0.30,
    horizontal_flip=True,
    brightness_range=[0.8, 1.2],
    fill_mode="nearest",
)

# Read data from directory
train_data = train_aug.flow_from_directory(
    train_dir,
    target_size=(Image_size, Image_size),
    batch_size=BATCH_SIZE,
    class_mode="categorical"
)

# Augmentations for test data
test_aug = ImageDataGenerator(
    preprocessing_function=preprocess_input
)

# Read data from directory
test_data = test_aug.flow_from_directory(
    test_dir,
    target_size=(Image_size, Image_size),
    batch_size=BATCH_SIZE,
    class_mode="categorical"
)

categories = list(train_data.class_indices.keys())
num_classes = len(categories)
print(f"Total categories: {num_classes}")
print(f"Categories: {categories}")

import tensorflow as tf
from tensorflow.keras.applications import ResNet50
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense, Input, GlobalAveragePooling2D, Dropout


# Load the ResNet50 model
resnet_base = tf.keras.applications.ResNet50(include_top=False,
                   input_shape=(Image_size,Image_size,3),
                   weights='imagenet')

resnet_base.trainable=True

for layer in resnet_base.layers[:-50]:
  layer.trainable = False

# Define the input layer for the model
inputs = Input(shape=(Image_size,Image_size,3))
x = resnet_base(inputs, training=False)

# Add custom classification layers
x = GlobalAveragePooling2D()(x)
x = Dense(256, activation='relu')(x)
x = Dropout(0.5)(x)
x = Dense(128, activation='relu')(x)
x = Dropout(0.5)(x)
outputs = Dense(num_classes, activation='softmax')(x)


model = Model(inputs, outputs)
model.summary()

from tensorflow.keras.optimizers import Adam
model.compile(
    optimizer=Adam(learning_rate=1e-4),
    loss='categorical_crossentropy',
    metrics=['accuracy']
    )

from tensorflow.keras.callbacks import EarlyStopping

early_stop = EarlyStopping(
    monitor='val_loss',
    patience=3,
    restore_best_weights=True
)

history = model.fit(
  train_data,
  validation_data=test_data,
  epochs=25,
  callbacks=[early_stop]
)

model.save("LeafDiseaseResNet50.h5")

from google.colab import files
files.download("/content/LeafDiseaseResNet50.h5")